dist: xenial
sudo: false
language: python
# cache: pip
#
# Matrix composition:
# Django LTS versions: All supported Python releases
# Other versions and master branch: The newest possible Python release
python:
  - 3.7
matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
    - python: 3.7
      env: REQ="Django>=2.2,<3.0"
    - python: 3.6
      env: REQ="Django>=2.2,<3.0"
    - python: 3.5
      env: REQ="Django>=2.2,<3.0"
    - python: 3.7
      env: REQ="Django>=2.1,<2.2"
    - python: 3.7
      env: REQ="Django>=2.0,<2.1"
    - python: 3.7
      env: REQ="Django>=1.11,<2.0"
    - python: 3.6
      env: REQ="Django>=1.11,<2.0"
    - python: 3.5
      env: REQ="Django>=1.11,<2.0"
    - python: 3.4
      env: REQ="Django>=1.11,<2.0"
    - python: 3.7
      env: REQ="black flake8"
      install: skip
      script:
        - pip install black flake8
        - flake8 .
        - black --check translated_fields tests
  allow_failures:
    - env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
install:
- pip install -U pip wheel
- pip install $REQ
- python setup.py install
script: cd tests && ./manage.py test testapp && cd ..
