sudo: false
cache: pip
language: python
python:
  - "3.5"
  - "3.6"
env:
  - DJANGO="Django>=1.11,<2.0"
  - DJANGO="Django>=2.0,<2.1"
install:
  - nvm install 7
  - pip install -U pip wheel flake8 isort unify
  - pip install $DJANGO -e .[tests]
  - pip freeze
script:
  - pytest
  - flake8
  - isort --check-only --diff --recursive translated_fields tests
  - unify --check-only --recursive --quote \' translated_fields tests
